/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Message {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface PortfolioItem {
  'url' : string,
  'title' : string,
  'context' : string,
  'date' : Time,
  'category' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'addPortfolioItem' : ActorMethod<
    [string, string, string, string, Time],
    undefined
  >,
  'getAllMessages' : ActorMethod<[Principal], Array<Message>>,
  'getAllPageContent' : ActorMethod<[], Array<[string, string]>>,
  'getAllPortfolioItems' : ActorMethod<[], Array<PortfolioItem>>,
  'getPageContent' : ActorMethod<[string], string>,
  'getPortfolioByCategory' : ActorMethod<[string], Array<PortfolioItem>>,
  'submitContactForm' : ActorMethod<[string, string, string], undefined>,
  'updatePageContent' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];