/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Message = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const PortfolioItem = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'context' : IDL.Text,
  'date' : Time,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'addPortfolioItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Time],
      [],
      [],
    ),
  'getAllMessages' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
  'getAllPageContent' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getAllPortfolioItems' : IDL.Func([], [IDL.Vec(PortfolioItem)], ['query']),
  'getPageContent' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getPortfolioByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PortfolioItem)],
      ['query'],
    ),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updatePageContent' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Message = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const PortfolioItem = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'context' : IDL.Text,
    'date' : Time,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'addPortfolioItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Time],
        [],
        [],
      ),
    'getAllMessages' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
    'getAllPageContent' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getAllPortfolioItems' : IDL.Func([], [IDL.Vec(PortfolioItem)], ['query']),
    'getPageContent' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getPortfolioByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PortfolioItem)],
        ['query'],
      ),
    'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updatePageContent' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };